made workflow activate on dispatch received

diff --git a/.github/workflows/releaser.yml b/.github/workflows/releaser.yml
--- a/.github/workflows/releaser.yml
+++ b/.github/workflows/releaser.yml
@@ -1,9 +1,8 @@
 name: Push Installer to s3
 
 on:
-  push:
-    branches:
-      - karan_installer # Placeholder for now, should activate on release in femr repo
+  repository_dispatch:
+    types: [generate-installer]
 
 jobs:
   release:
@@ -18,12 +17,12 @@ jobs:
           python-version: "3.10"
           cache: "pip"
       - run: pip install -r requirements.txt
-      - run: python release.py --version 3.0.0
+      - run: python release.py --version ${{ github.event.client_payload.version }}
 
       - name: Check if an installer file is present
         run: |
           if [ -n "$(ls -A macOS-x64/target/pkg/ 2>/dev/null)" ]; then 
-            echo "Installer is present"; 
+            echo "Installer successfully generated. Check s3 bucket to verify."; 
           else 
-            echo "Installer is missing" && exit 1; 
+            echo "Installer is missing." && exit 1; 
           fi
