adjusted workflow

diff --git a/.github/workflows/releaser.yml b/.github/workflows/releaser.yml
--- a/.github/workflows/releaser.yml
+++ b/.github/workflows/releaser.yml
@@ -8,7 +8,7 @@ on:
 jobs:
   release:
     name: Run release.py
-    runs-on: macos-13
+    runs-on: macos-13 # Have to use macos runner due to the use of pkgbuild in build script
     steps:
       - uses: actions/checkout@v4
       - name: Setup Docker on macOS
@@ -19,3 +19,11 @@ jobs:
           cache: "pip"
       - run: pip install -r requirements.txt
       - run: python release.py --version 3.0.0
+
+      - name: Check if the installer is present
+        run: |
+          if [ -f "macOS-x64/target/pkg/installer.pkg" ]; then 
+            echo "Installer is present"; 
+          else 
+            echo "Installer is missing" && exit 1; 
+          fi
